### PR TITLE
Update Freedesktop runtime to the latest (23.08) version

### LINKED ISSUE #56: Update Freedesktop runtime to the latest (23.08) version

### PR DESCRIPTION
**Pull request by x80486**
Closes #56

### CODE REVIEW

**Comment by x80486** [comment]
Will have to wait for [org.electronjs.Electron2.BaseApp/issues/43](https://github.com/flathub/org.electronjs.Electron2.BaseApp/issues/43) :man_shrugging:

**Comment by bbhtt** [comment]
23.08 baseapp is out now.

Can you check if desktop notifications work without `--talk-name=org.freedesktop.Notifications`?

The 23.08 baseapp includes libnotify 0.8.2 which should not require that hole.

**Comment by x80486** [comment]
bot, build

**Comment by x80486** [comment]
> 23.08 baseapp is out now.
> 
> Can you check if desktop notifications work without `--talk-name=org.freedesktop.Notifications`?
> 
> The 23.08 baseapp includes libnotify 0.8.2 which should not require that hole.

I'm not using `Wire` anymore, though I'm still "maintaining" this package until someone steps in. I can create a pull request for this change, and whenever you have some time you can let me know if it works without `--talk-name=org.freedesktop.Notifications`, or not.

**Pull request merged**
