### PR TITLE
Remove ability to talk to org.freedesktop.Notifications service on the session bus

### PR DESCRIPTION
**Pull request by x80486**

### CODE REVIEW

**Comment by x80486** [comment]
@bbhtt, whenever you have some time let me know if this works.

**Comment by bbhtt** [comment]
I can check in a bit, I don't have a wire account but I can make one to test

**Comment by bbhtt** [comment]
Yep works, tested!

**Comment by bbhtt** [comment]
Fwiw, libnotify already uses the portal backend inside the sandbox when the runtime got upgraded since 23.08 has libnotify 0.8.

This was just about removing the leftover.

**Comment by bbhtt** [comment]
Hey @x80486 we fixed a bug in libnotify that was causing applications on Electron baseapp 23.08 to crash https://github.com/flathub/org.electronjs.Electron2.BaseApp/pull/48

If you can trigger a rebuild via https://buildbot.flathub.org/#/ it'd be great.

**Pull request merged**
